# =============================================================================
# Compare two fixture sets generated from the frozen tag, typically the
# committed fixtures (fixture platform) and fixtures regenerated by
# tools/frozen/make_fixtures.R on another platform.
#
# Usage (from the package root):
#   Rscript tools/frozen/compare_fixtures.R <reference_dir> <candidate_dir>
#
# This compares the FROZEN implementation with itself across platforms; the
# package is not involved. Deterministic components must agree within the
# documented tolerance tiers (PACKAGE_PLAN.md section 9.2); a difference
# beyond tolerance makes the script exit with status 1.
#
# Bootstrap-draw fixtures (fx_bootstrap, and T.boot / p.value / atom.zero in
# fx_test_sigma_nested) depend on LAPACK/BLAS through MASS::mvrnorm(). They
# are reported but never fail the comparison.
# =============================================================================

source(file.path("tests", "testthat", "helper-compare.R"))

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2L) {
  stop("Usage: Rscript tools/frozen/compare_fixtures.R <reference_dir> <candidate_dir>")
}

ref_dir <- args[1]
cand_dir <- args[2]

tiers <- list(
  fx_source = TOL_T0,
  fx_matrix = TOL_T2,
  fx_covariance = TOL_T2,
  fx_interval_balance = TOL_T2,
  fx_fit = TOL_T2,
  fx_crank_nicolson = TOL_T1,
  fx_real_mesc = TOL_T2
)

platform_dependent <- c("fx_bootstrap")
boot_fields <- c("T.boot", "p.value", "atom.zero", "bootstrap.failure.rate",
                 "n.bootstrap.valid", "bootstrap.condition.median",
                 "bootstrap.condition.q95", "bootstrap.condition.max",
                 "bootstrap.rank.deficient.fraction")

rows <- list()
record <- function(fixture, case, part, ok, blocking, detail = "") {
  rows[[length(rows) + 1L]] <<- data.frame(
    fixture = fixture, case = case, part = part, ok = ok,
    blocking = blocking, detail = detail
  )
}

files <- sort(list.files(ref_dir, pattern = "\\.rds$"))
stopifnot(identical(files, sort(list.files(cand_dir, pattern = "\\.rds$"))))

for (f in files) {
  fixture <- sub("\\.rds$", "", f)
  ref <- readRDS(file.path(ref_dir, f))
  cand <- readRDS(file.path(cand_dir, f))
  stopifnot(identical(ref$provenance$frozen_commit, cand$provenance$frozen_commit))
  stopifnot(identical(names(ref$cases), names(cand$cases)))

  for (key in names(ref$cases)) {
    r <- ref$cases[[key]]
    c <- cand$cases[[key]]

    if (fixture %in% platform_dependent) {
      p <- compare_close(c$output, r$output, TOL_T2)
      record(fixture, key, "output", length(p) == 0L, FALSE,
             paste(utils::head(p, 3), collapse = "; "))
      next
    }

    if (fixture == "fx_test_sigma_nested") {
      pin <- compare_close(c$input, r$input, TOL_T2)
      record(fixture, key, "input", length(pin) == 0L, TRUE,
             paste(utils::head(pin, 3), collapse = "; "))
      rv <- r$output$value
      cv <- c$output$value
      det <- setdiff(names(rv), boot_fields)
      pd <- compare_close(cv[det], rv[det], TOL_T2)
      record(fixture, key, "deterministic fields", length(pd) == 0L, TRUE,
             paste(utils::head(pd, 3), collapse = "; "))
      bf <- intersect(boot_fields, names(rv))
      pb <- compare_close(cv[bf], rv[bf], TOL_T2)
      record(fixture, key, "bootstrap fields", length(pb) == 0L, FALSE,
             paste(utils::head(pb, 3), collapse = "; "))
      next
    }

    tol <- tiers[[fixture]]
    pin <- compare_close(c$input, r$input, TOL_T2)
    record(fixture, key, "input", length(pin) == 0L, TRUE,
           paste(utils::head(pin, 3), collapse = "; "))
    pout <- compare_close(c$output, r$output, tol)
    record(fixture, key, "output", length(pout) == 0L, TRUE,
           paste(utils::head(pout, 3), collapse = "; "))
  }
}

res <- do.call(rbind, rows)

summary_tab <- do.call(rbind, lapply(split(res, list(res$fixture, res$part),
                                           drop = TRUE), function(x) {
  data.frame(fixture = x$fixture[1], part = x$part[1], blocking = x$blocking[1],
             compared = nrow(x), within_tolerance = sum(x$ok))
}))

cat("Reference provenance: ", readRDS(file.path(ref_dir, files[1]))$provenance$platform,
    "/", readRDS(file.path(ref_dir, files[1]))$provenance$La_library, "\n")
cat("Candidate provenance: ", readRDS(file.path(cand_dir, files[1]))$provenance$platform,
    "/", readRDS(file.path(cand_dir, files[1]))$provenance$La_library, "\n\n")
print(summary_tab[order(summary_tab$fixture, summary_tab$part), ], row.names = FALSE)

bad <- res[res$blocking & !res$ok, ]
info <- res[!res$blocking & !res$ok, ]

if (nrow(info) > 0L) {
  cat("\nPlatform-dependent differences (reported, not blocking):",
      nrow(info), "\n")
}

if (nrow(bad) > 0L) {
  cat("\nDETERMINISTIC DIFFERENCES BEYOND TOLERANCE:\n")
  print(utils::head(bad, 50), row.names = FALSE)
  if (identical(Sys.getenv("GITHUB_ACTIONS"), "true")) {
    esc <- function(x) gsub("\n", "%0A", gsub("%", "%25", x, fixed = TRUE),
                            fixed = TRUE)
    for (grp in split(bad, paste(bad$fixture, bad$part))) {
      body <- paste(utils::head(sprintf("%s: %s", grp$case, grp$detail), 12),
                    collapse = "\n")
      cat(sprintf("::error title=%s %s (%d cases beyond tolerance)::%s\n",
                  grp$fixture[1], grp$part[1], nrow(grp), esc(body)))
    }
  }
  quit(status = 1L)
}

cat("\nAll deterministic frozen-reference components agree within tolerance.\n")
